# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-11 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0002_oc_age1'),
    ]

    operations = [
        migrations.AddField(
            model_name='oc',
            name='age2',
            field=models.IntegerField(default=10),
        ),
    ]
